Added deposit & withdraw functions to web app. Created unit test to verify methods
PROG17/JensBankWebApp pull request #2
Opened 2018-11-11 20:41 UTC by JensMHe

Added deposit & withdraw functions to web app. Created unit test to verify methods.

2018-11-11 20:42 UTC, JensMHe commented
Please review my pull request.

2018-11-12 10:00 UTC, egisan requested changes
Everything works fine. I noticed a small bug when you try to perform a withdrawal in order to get a balance equal to 0. Can you please fix it?

2018-11-12 10:16 UTC, JensMHe commented
Ok, issue solved in new commit

2018-11-12 10:18 UTC, egisan commented
Well done Jens!

I verified following:

Det ska finnas unit tester för insättning, uttag och för stort uttag.
Det finns en länk till sidan för insättning och uttag
Om man skriver in ett kontonummer och belopp ska saldot på angivet konto ökas eller minskas beroende på om man trycker på insättnings eller uttagsknappen.
Det ska synas ett felmeddelande om man skriver in ett kontonummer som inte finns
Det ska synas ett felmeddelande om man försöker ta ut mer pengar än det finns
Det ska synas ett felmeddelande om beloppet inte är korrekt formaterat

2018-11-12 10:18 UTC, egisan approved these changes

2018-11-12 10:25 UTC, merged